-- Insert sample dogs
INSERT INTO public.dogs (name, age, breed, size, gender, location, bio, shelter_name, personality, health_status, is_good_with_kids, is_good_with_pets, energy_level, image_urls, traits) VALUES
('Max', 3, 'Golden Retriever', 'large', 'male', 'Seoul, Gangnam', 'Max is a friendly and energetic Golden Retriever who loves to play fetch and go on long walks. He''s great with kids and other dogs!', 'Seoul Animal Shelter', 'Friendly, playful, loyal', 'Healthy, vaccinated, neutered', true, true, 'high', ARRAY['https://images.unsplash.com/photo-1633722715463-d30f4f325e24', 'https://images.unsplash.com/photo-1625794084867-8ddd239946b1'], ARRAY['Friendly', 'Energetic', 'Loves Water']),

('Luna', 2, 'Shiba Inu', 'medium', 'female', 'Seoul, Hongdae', 'Luna is an independent but loving Shiba Inu. She enjoys quiet time but also loves her daily walks in the park.', 'Happy Paws Rescue', 'Independent, intelligent, alert', 'Healthy, spayed, all shots up to date', false, false, 'medium', ARRAY['https://images.unsplash.com/photo-1568572933382-74d440642117', 'https://images.unsplash.com/photo-1567225591450-06036b3392a6'], ARRAY['Independent', 'Smart', 'Clean']),

('Buddy', 5, 'Labrador Mix', 'large', 'male', 'Seoul, Itaewon', 'Buddy is a gentle giant who loves everyone he meets. He''s house-trained and knows basic commands.', 'Seoul Dog Rescue', 'Gentle, calm, affectionate', 'Healthy, some arthritis in hind legs', true, true, 'low', ARRAY['https://images.unsplash.com/photo-1588943211346-0908a1fb0b01', 'https://images.unsplash.com/photo-1587300003388-59208cc962cb'], ARRAY['Gentle', 'Senior', 'Calm']),

('Daisy', 1, 'Pomeranian', 'small', 'female', 'Seoul, Myeongdong', 'Daisy is a fluffy ball of energy! She loves to be the center of attention and will follow you everywhere.', 'Furry Friends Seoul', 'Playful, affectionate, attention-seeking', 'Healthy, recent dental cleaning', true, false, 'high', ARRAY['https://images.unsplash.com/photo-1581888227599-779811939961', 'https://images.unsplash.com/photo-1582456891925-a53965f8af43'], ARRAY['Fluffy', 'Playful', 'Lap Dog']),

('Rocky', 4, 'German Shepherd Mix', 'large', 'male', 'Seoul, Jamsil', 'Rocky is a loyal and intelligent dog who would make an excellent companion for an active family.', 'K9 Rescue Korea', 'Loyal, protective, intelligent', 'Healthy, needs regular exercise', true, true, 'high', ARRAY['https://images.unsplash.com/photo-1589941013453-ec89f33b5e95', 'https://images.unsplash.com/photo-1568393691622-c7ba131d63b4'], ARRAY['Protective', 'Smart', 'Active']),

('Bella', 2, 'Maltese', 'small', 'female', 'Seoul, Gangnam', 'Bella is a sweet and gentle Maltese who loves cuddles and being pampered. Perfect for apartment living!', 'Seoul Small Dog Rescue', 'Sweet, gentle, quiet', 'Healthy, regular grooming needed', true, true, 'low', ARRAY['https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e', 'https://images.unsplash.com/photo-1604165094774-a28f53a8a2d0'], ARRAY['Gentle', 'Quiet', 'Apartment Friendly']),

('Charlie', 3, 'Beagle', 'medium', 'male', 'Seoul, Dongdaemun', 'Charlie is a curious Beagle with a nose for adventure. He loves exploring and would enjoy a home with a yard.', 'Beagle Rescue Korea', 'Curious, friendly, food-motivated', 'Healthy, tendency to overeat', true, true, 'medium', ARRAY['https://images.unsplash.com/photo-1505628346881-b72b27e84530', 'https://images.unsplash.com/photo-1563889362352-b0492c224320'], ARRAY['Curious', 'Food Lover', 'Vocal']),

('Mochi', 1, 'Corgi', 'medium', 'female', 'Seoul, Insadong', 'Mochi is an adorable Corgi puppy full of energy and sass. She''s learning basic commands and is very treat motivated!', 'Corgi Love Korea', 'Energetic, sassy, playful', 'Healthy, needs training', true, true, 'high', ARRAY['https://images.unsplash.com/photo-1546975490-e8b92a360b24', 'https://images.unsplash.com/photo-1519098901909-b1553a1190af'], ARRAY['Sassy', 'Puppy', 'Stubby Legs']);